dubbo:
  application:
    name: boot-dubbo-user-service
  registry:
    protocol: zookeeper
    address: 192.168.0.110:2182,192.168.0.110:2181,192.168.0.110:2183
  protocol:
    name: dubbo
    port: 20210

